import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head1 from "./components/Head1/Head1";
import Head2 from "./components/Head2/Head2";
import Footer from "./components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "dentistry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Head1/>
        <Head2/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
